[package]
name = "wire"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
contentstore = { workspace = true }
rustls = { workspace = true }
rcgen = { workspace = true }
blake3 = { workspace = true }
jobfmt = { workspace = true }
