[package]
name = "coordinator"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
rvcore = { workspace = true }
contentstore = { workspace = true }
wire = { workspace = true }
jobfmt = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ed25519-dalek = { workspace = true }
rand_core = { workspace = true }
blake3 = { workspace = true }
rustls = { workspace = true }

[dev-dependencies]
worker = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = "0.10"
